apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugfixerapp-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugfixerapp
  template:
    metadata:
      labels:
        app: bugfixerapp
    spec:
      containers:
      - name: bugfixer-app
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $GCLOUD_PROJECT with your project ID.
        image: anubhuti231227/bugfixerapp:0.0.5.RELEASE
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"